### ISSUE TITLE
share file method error 

### ISSUE THREAD

**Issue by mini0555555** [ankushmishra2903-official/whatsapp_share2#21]
W/Bundle  ( 8374): Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
W/Bundle  ( 8374): Attempt to cast generated internal exception:
W/Bundle  ( 8374): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
W/Bundle  ( 8374): 	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1351)
W/Bundle  ( 8374): 	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1145)
W/Bundle  ( 8374): 	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:8383)
W/Bundle  ( 8374): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:11402)
W/Bundle  ( 8374): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1721)
W/Bundle  ( 8374): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1055)
W/Bundle  ( 8374): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1013)
W/Bundle  ( 8374): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:413)
W/Bundle  ( 8374): 	at com.example.whatsapp_share.WhatsappShare.shareFile(WhatsappShare.java:218)
W/Bundle  ( 8374): 	at com.example.whatsapp_share.WhatsappShare.onMethodCall(WhatsappShare.java:60)
W/Bundle  ( 8374): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
W/Bundle  ( 8374): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/Bundle  ( 8374): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
W/Bundle  ( 8374): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/Bundle  ( 8374): 	at android.os.Handler.handleCallback(Handler.java:938)
W/Bundle  ( 8374): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/Bundle  ( 8374): 	at android.os.Looper.loop(Looper.java:264)
W/Bundle  ( 8374): 	at android.app.ActivityThread.main(ActivityThread.java:8312)
W/Bundle  ( 8374): 	at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  ( 8374): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
W/Bundle  ( 8374): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by DevloperAnuj** [comment]
Facing Same problem !

W/Bundle  (20715): Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
W/Bundle  (20715): Attempt to cast generated internal exception:
W/Bundle  (20715): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
