### ISSUE TITLE
Unhandled Exception: PlatformException(Failed to find configured root that contains

### ISSUE THREAD

**Issue by droidzone** [ankushmishra2903-official/whatsapp_share2#6]
```
E/flutter (28040): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(Failed to find configured root that contains /data/data/com.droidzone.myopipclinic/cache/prescription.pdf, null, null, null)
E/flutter (28040): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (28040): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177:18)
E/flutter (28040): <asynchronous suspension>
E/flutter (28040): #2      WhatsappShare.shareFile (package:whatsapp_share2/whatsapp_share2.dart:78:9)
E/flutter (28040): <asynchronous suspension>
E/flutter (28040): #3      _EMRScreenState.sharePDFDirectly (package:myopipclinic/screens/emr_screen.dart:276:5)
E/flutter (28040): <asynchronous suspension>
E/flutter (28040): 
```

Getting this exception when trying to share files

```
  Future sharePDFDirectly() async {
    await hasStoragePermissions();
    String tempdirPath = await getdir();
    var link = await connection.getPrescriptionLink(
      checkinID: checkIn.checkinno,
    );
    print(
        "sharePDFDirectly:: response in getPrescription: $link type:${link.runtimeType}");
    // First send a message to the customer, so that the next step of sharing the pdf goes to the right recipient.

    Dio dio = Dio();
    String fpath = tempdirPath + "/prescription.pdf";
    Response retData = await dio.download(link, fpath);
    print("Downloaded prescription before sharing through Whatsapp to $fpath");
    List<String> filePaths = [];
    filePaths.add(fpath);

    await WhatsappShare.shareFile(
      text: 'Whatsapp share text',
      phone: '91${customer.mobile}',
      filePath: filePaths,
    );
```

**Comment by devangichhatbar** [comment]
Please try using the below link. 

https://stackoverflow.com/a/56186903/8197867

**Comment by karebmusu** [comment]
which path should i use? @devangichhatbar

**Comment by smit-sk** [comment]
Make sure whatsaap is installed
